
language: cpp

script: make

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

matrix:
  include:
    - os: linux
      env: CXX=g++-5
    - os: osx
      osx_image: xcode7.3

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang
