script: make

compiler:
  - clang-3.7

env:
  - CXX=clang-3.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-5
    - g++-5
    - clang-3.7
