
language: cpp

script: make

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
          - libcxx
          - libcxx-dev
    - os: osx
      osx_image: xcode7.2
