script: make

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5
      env:
        CXX=g++-5
    - os: osx
      osx_image: xcode7.2

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang
