
language: cpp

script: make

os:
  - linux
  - osx

env:
  - CXX=g++-5
  - CXX=clang++

matrix:
  include:
    - os: linux
      env: CXX=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
    - os: osx
      env: CXX=clang++
      osx_image: xcode7.3
  exclude:
    - os: osx
      env: CXX=g++-5
    - os: linux
      env: CXX=clang++
